Given:
class Fork {
	public static void main(String[] args) {
		if(args.length == 1 | args[1].equals("test")) {
			System.out.println("test case");
		} else {
			System.out.println("production " + args[0]);
		}
	}
}
And the command-line invocation:
java Fork live2

What is the result?
A. test case
B. production live2
C. test case live2
D. Compilation fails
E. An exception is thrown at runtime





















































Answer:
E is correct. Because the short circuit (||) is not used, 
both operands are evaluated. Since args[1] is past the args
 array bounds, an ArrayIndexOutOfBoundsException is thrown.
A, B, C, and D are incorrect based on the above. (Objective 7.6)



Mi Respuetsa
Ok la tube bien pero porque pense que lanzaría un 
NullPointerExcpetion pero lanza un ArrayIndexOfBoundException
lo cual esta bien porque tratas de acceder  una posición
que no existe, si exisitriera pero fuera null
entonces ahora si lanzaria el NullPointer, aun asi si la tuve
bien.